// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TUROAPI.Context;

#nullable disable

namespace TUROAPI.Migrations
{
    [DbContext(typeof(TuroDBContext))]
    [Migration("20260922061733_change-id-refresh-token")]
    partial class changeidrefreshtoken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CombinationTable", b =>
                {
                    b.Property<Guid>("CombinationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TablesId")
                        .HasColumnType("uuid");

                    b.HasKey("CombinationsId", "TablesId");

                    b.HasIndex("TablesId");

                    b.ToTable("CombinationTable");
                });

            modelBuilder.Entity("TUROAPI.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CombinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("CombinationId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TableId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TUROAPI.Models.CancellationConditions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RestaurantId");

                    b.ToTable("CancellationConditions");
                });

            modelBuilder.Entity("TUROAPI.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Tags")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TUROAPI.Models.Closure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerMessage")
                        .HasColumnType("text");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonDetail")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Closures");
                });

            modelBuilder.Entity("TUROAPI.Models.Combination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeactivateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Combinations");
                });

            modelBuilder.Entity("TUROAPI.Models.Decor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Decors");
                });

            modelBuilder.Entity("TUROAPI.Models.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReservationId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("TUROAPI.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DestroyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TUROAPI.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CancellationConditionsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConditionsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedByClientAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Covers")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreferredZoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SeatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ServiceDay")
                        .HasColumnType("date");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CancellationConditionsId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PreferredZoneId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TUROAPI.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoConfirmation")
                        .HasColumnType("boolean");

                    b.Property<int>("DefaultRotation")
                        .HasColumnType("integer");

                    b.Property<int>("LateGrace")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReminderDelayHours")
                        .HasColumnType("integer");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SeatTolerance")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("TUROAPI.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Closing")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("CoverCap")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxCadence")
                        .HasColumnType("integer");

                    b.Property<int>("OccupancyMode")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Opening")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("TUROAPI.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NeedsCleaningSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision");

                    b.Property<int>("Shape")
                        .HasColumnType("integer");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("TUROAPI.Models.UserStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("UserStaffs");
                });

            modelBuilder.Entity("TUROAPI.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("CombinationTable", b =>
                {
                    b.HasOne("TUROAPI.Models.Combination", null)
                        .WithMany()
                        .HasForeignKey("CombinationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUROAPI.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TUROAPI.Models.Assignment", b =>
                {
                    b.HasOne("TUROAPI.Models.UserStaff", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById");

                    b.HasOne("TUROAPI.Models.Combination", "Combination")
                        .WithMany("Assignments")
                        .HasForeignKey("CombinationId");

                    b.HasOne("TUROAPI.Models.Reservation", "Reservation")
                        .WithMany("Assignments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUROAPI.Models.Table", "Table")
                        .WithMany("Assignments")
                        .HasForeignKey("TableId");

                    b.Navigation("AssignedBy");

                    b.Navigation("Combination");

                    b.Navigation("Reservation");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TUROAPI.Models.CancellationConditions", b =>
                {
                    b.HasOne("TUROAPI.Models.UserStaff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("CancellationConditions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Client", b =>
                {
                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Clients")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Closure", b =>
                {
                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Closures")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TUROAPI.Models.ReplacementHours", "ReplacementHours", b1 =>
                        {
                            b1.Property<Guid>("ClosureId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<TimeOnly>("Closing");

                            b1.Property<TimeOnly>("Opening");

                            b1.HasKey("ClosureId", "__synthesizedOrdinal");

                            b1.ToTable("Closures");

                            b1
                                .ToJson("ReplacementHours")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ClosureId");
                        });

                    b.Navigation("ReplacementHours");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Combination", b =>
                {
                    b.HasOne("TUROAPI.Models.Zone", "Zone")
                        .WithMany("Combinations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TUROAPI.Models.Decor", b =>
                {
                    b.HasOne("TUROAPI.Models.Zone", "Zone")
                        .WithMany("Decors")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TUROAPI.Models.EventLog", b =>
                {
                    b.HasOne("TUROAPI.Models.UserStaff", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TUROAPI.Models.Reservation", "Reservation")
                        .WithMany("Events")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("TUROAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("TUROAPI.Models.UserStaff", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TUROAPI.Models.Reservation", b =>
                {
                    b.HasOne("TUROAPI.Models.CancellationConditions", "CancellationConditions")
                        .WithMany()
                        .HasForeignKey("CancellationConditionsId");

                    b.HasOne("TUROAPI.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId");

                    b.HasOne("TUROAPI.Models.Zone", "PreferredZone")
                        .WithMany()
                        .HasForeignKey("PreferredZoneId");

                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancellationConditions");

                    b.Navigation("Client");

                    b.Navigation("PreferredZone");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Service", b =>
                {
                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Services")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Table", b =>
                {
                    b.HasOne("TUROAPI.Models.Zone", "Zone")
                        .WithMany("Tables")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TUROAPI.Models.UserStaff", b =>
                {
                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Users")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Zone", b =>
                {
                    b.HasOne("TUROAPI.Models.Restaurant", "Restaurant")
                        .WithMany("Zones")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("TUROAPI.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TUROAPI.Models.Combination", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TUROAPI.Models.Reservation", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("TUROAPI.Models.Restaurant", b =>
                {
                    b.Navigation("CancellationConditions");

                    b.Navigation("Clients");

                    b.Navigation("Closures");

                    b.Navigation("Reservations");

                    b.Navigation("Services");

                    b.Navigation("Users");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("TUROAPI.Models.Table", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TUROAPI.Models.Zone", b =>
                {
                    b.Navigation("Combinations");

                    b.Navigation("Decors");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
